
workspace = true
replace-version = true
publish = true
push = true
tag = true

consolidate-commits = true
consolidate-pushes = true
sign-tag = false

pre-release-commit-message = "chore(release): prepare {{crate_name}} {{version}}"
tag-message = "Release {{crate_name}} {{version}}"

# Optional but helpful for cyclic dependencies
publish-order = ["rpgx", "rpgx-wasm", "rpgx-dioxus"]

exclude = ["rpgx-spaceship"]