[workspace]
resolver = "3"
members = [
    "packages/core",
    "packages/rpgxw",
    "packages/drivers/dioxus",
    "playground/dioxus",
]

[profile]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
