release = true
publish = true
push = true
tag = true

consolidate-commits = true
sign-tag = false

pre-release-commit-message = "chore(release): prepare {crate_name} {version}"
tag-message = "Release {crate_name} {version}"
