[package]
name = "rpgx-wasm"
version = "0.1.0"
edition = "2024"

[dependencies]
js-sys = "0.3.77"
rpgx = { path = "../../core" }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4.50"

[lib]
crate-type = ["cdylib", "rlib"]
