[package]
name = "rpgx"
version = "0.1.5"
edition = "2024"
authors = ["Lorenzo Rottigni <lorenzo@rottigni.tech>"]
description = "Lightweight, modular, and extensible RPG game engine 2D, designed for flexibility, portability, and ease of use."
repository = "https://github.com/LorenzoRottigni/rpgx"
homepage = "https://github.com/LorenzoRottigni/rpgx"
documentation = "https://docs.rs/rpgx"
readme = "README.md"
license = "MIT"

[lib]
name = "rpgx"
path = "src/lib.rs"
crate-type = ["rlib"]

[features]
default = []
presets = []

[dependencies]
indexmap = "2.9.0"

[dev-dependencies]
futures = "0.3.31"
