[package]
name = "rpgx-dioxus"
version = "0.1.0"
edition = "2024"

[dependencies]
# Shared
dioxus = { version = "0.6.3", features = ["router", "fullstack"] }
dioxus-logger = "0.6.2"
futures-util = "0.3.31"
rpgx = { path = "../../rpgx" }
log = "0.4.27"

# --- Web-only dependencies ---
gloo-timers = { version = "0.3", features = ["futures"], optional = true }
web-sys = { version = "0.3.77", optional = true }
wasm-bindgen = { version = "0.2.92", optional = true }
js-sys = { version = "0.3.67", optional = true }

# --- Desktop-only dependencies ---
tokio = { version = "1.45.0", optional = true }

[features]
default = []

# Feature for web builds
web = [
  "dioxus/web",
  "gloo-timers",
  "web-sys",
  "wasm-bindgen",
  "js-sys"
]

# Feature for desktop builds
desktop = [
  "dioxus/desktop",
  "tokio"
]

# Optional support for mobile builds
mobile = ["dioxus/mobile"]
