name: Build and Test

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Linux WebView prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-dev \
            libwebkit2gtk-4.1-dev \
            libsoup2.4-dev \
            libgdk-pixbuf2.0-dev \
            libpango1.0-dev \
            pkg-config

      - name: Set up Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rust-version: '1.56'

      - name: Install WebAssembly target
        run: rustup target add wasm32-unknown-unknown

      - name: Install wasm-bindgen CLI
        run: cargo install wasm-bindgen-cli --locked

      - name: Run Builds and Tests
        run: |
          make build-all
          make test-all
