name: Run Builds

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Enable Jammy repos for WebKitGTK
        run: |
          # Add Jammy (22.04) main & universe to apt sources
          echo "deb http://archive.ubuntu.com/ubuntu jammy main universe" | sudo tee /etc/apt/sources.list.d/jammy.list
          sudo apt-get update

      - name: Install Dioxus Desktop dependencies
        run: |
          # (Optional) add Ubuntu Jammy for WebKitGTK 4.0 on Ubuntu ≥24.04
          echo "deb http://archive.ubuntu.com/ubuntu jammy main universe" | sudo tee /etc/apt/sources.list.d/jammy.list

          sudo apt-get update

          sudo apt-get install -y \
            pkg-config \
            libdbus-1-dev \
            libgtk-3-dev \
            libwebkit2gtk-4.0-dev \
            libjavascriptcoregtk-4.0-dev \
            libsoup2.4-dev \
            libpango1.0-dev \
            libatk1.0-dev \
            libgdk-pixbuf2.0-dev \
            libcairo2-dev \
            libx11-dev \
            libglib2.0-dev \
            libxdo-dev \
            libappindicator3-dev \
            zenity

      - name: Set up Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rust-version: 'nightly'

      - name: Install wasm32-unknown-unknown target
        run: rustup target add wasm32-unknown-unknown

      - name: Install wasm-bindgen-cli
        run: |
          cargo install wasm-bindgen-cli --locked

      - name: Build
        run: |
          make build-all
