name: Run Tests

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: '1.56'
      - name: Run Tests
        run: make test-all
